# Generated by Django 5.1 on 2024-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chauffeur",
            name="annee_voiture",
            field=models.PositiveIntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name="chauffeur",
            name="couleur_voiture",
            field=models.CharField(
                choices=[
                    ("rouge", "Rouge"),
                    ("blanche", "Blanche"),
                    ("noir", "Noir"),
                    ("bleu", "Bleu"),
                    ("gris", "Grise"),
                ],
                default="blanche",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="chauffeur",
            name="marque_voiture",
            field=models.CharField(
                choices=[
                    ("mercedes", "Mercedes"),
                    ("bmw", "Bmw"),
                    ("toyota", "Toyota"),
                    ("range", "Range"),
                    ("hundai", "Hundai"),
                ],
                default="hundai",
                max_length=255,
            ),
        ),
    ]
