# Generated by Django 5.1 on 2024-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_chauffeur_annee_voiture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chauffeur",
            name="annee_voiture",
            field=models.PositiveIntegerField(),
        ),
    ]
