# Generated by Django 5.1 on 2024-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_chauffeur_annee_voiture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chauffeur",
            name="coordonnees",
            field=models.JSONField(default=list),
        ),
    ]
