# Generated by Django 5.1 on 2024-08-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_chauffeur_coordonnees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passager",
            name="coordonnees",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
